// <auto-generated />
using System;
<<<<<<<< HEAD:SongBird.Api/Migrations/20260620152948_initial8.Designer.cs
========
using SongBird.Api.Data;
>>>>>>>> 4d999cd96092e4c8bb3d8352eb2a200151c8a3d3:SongBird.Api/Migrations/20260416184907_init7.Designer.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongBird.Api.Data;

#nullable disable

namespace SongBird.Api.Migrations
{
    [DbContext(typeof(AppDBContext))]
<<<<<<<< HEAD:SongBird.Api/Migrations/20260620152948_initial8.Designer.cs
    [Migration("20260620152948_initial8")]
    partial class initial8
========
    [Migration("20260416184907_init7")]
    partial class init7
>>>>>>>> 4d999cd96092e4c8bb3d8352eb2a200151c8a3d3:SongBird.Api/Migrations/20260416184907_init7.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SongBird.Api.Models.VideoProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

<<<<<<<< HEAD:SongBird.Api/Migrations/20260620152948_initial8.Designer.cs
                    b.Property<bool>("IsShort")
                        .HasColumnType("bit");

========
>>>>>>>> 4d999cd96092e4c8bb3d8352eb2a200151c8a3d3:SongBird.Api/Migrations/20260416184907_init7.Designer.cs
                    b.Property<string>("LrcPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyricsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RenderProgress")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
